spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/movietickets
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
#        show_sql: true // system.out을 통해서 sql이 찍힘
          format_sql: true

logging:
  level:
    org.hibernate.SQL: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true